// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82fgmZ4kakVwtfQn7u3m1-sLWO5hTjM4',
    appId: '1:732914476826:android:95e7adbeb753cfae212ea3',
    messagingSenderId: '732914476826',
    projectId: 'reservoir-measure',
    databaseURL: 'https://reservoir-measure-default-rtdb.firebaseio.com',
    storageBucket: 'reservoir-measure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDunczghSeQ4UxRn4VrZErHDwwVUQUd0Z8',
    appId: '1:732914476826:ios:d49f66ca4153129f212ea3',
    messagingSenderId: '732914476826',
    projectId: 'reservoir-measure',
    databaseURL: 'https://reservoir-measure-default-rtdb.firebaseio.com',
    storageBucket: 'reservoir-measure.appspot.com',
    iosClientId: '732914476826-5nuapucp5vlg87ahmbefncrq4ferg0b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.measure',
  );
}
